image: python:3.6

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list
  - apt-get update -q
  # old versions of sqlite cause testing problems with Django 2.2
  - apt-get -t stretch-backports install sqlite3 -qy
  - python -V

test:
  script:
  - pip install -U pip setuptools
  - pip install -e .[test]
  # new versions of sqlite problems with Django < 2.2
  - tox -e "py36-django{20,21,22},style"
